# Nombre del proyecto
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# Perfil (debe coincidir con tu perfil de conexión de Snowflake en ~/.dbt/profiles.yml)
profile: 'default'

# Estructura de carpetas
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Carpeta donde dbt guarda archivos compilados y artefactos
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
   my_new_project:      # <- este debe coincidir con name
    +database: ALUMNO18_DEV_SILVER_DB
    +schema: SILVER

    silver:
      +materialized: view

      s_users:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: user_id

      s_orders:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: order_id

      s_order_items:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: ["order_id","product_id"]

      s_shipments:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: tracking_id

      s_events:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: event_id

      historico_precio:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: ["product_id","valid_from"]
