name: 'my_new_project'
version: '1.0.0'
config-version: 2

# Nombre del profile definido en tu ~/.dbt/profiles.yml
# (en dbt Cloud suele ser 'user' o 'default')
profile: 'default'

# Directorios de tu proyecto dbt
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Carpetas que dbt limpia en cada ejecución
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ============================================================
# CONFIGURACIÓN DE MODELOS Y CAPAS
# ============================================================

models:
  my_new_project:

    # ========================================================
    # CAPA SILVER (Staging)
    # ========================================================
    # Aquí viven los modelos limpios y normalizados que vienen
    # de las fuentes BRONZE. Estos son los s_*
    staging:
      +database: ALUMNO18_DEV_SILVER_DB
      +schema: SILVER
      +materialized: view  # Valor por defecto, pero puedes sobrescribirlo en cada modelo

      # Subcarpeta sql_server_dbo (tablas Fivetran desde SQL Server)
      sql_server_dbo:
        +database: ALUMNO18_DEV_SILVER_DB
        +schema: SILVER
        +materialized: incremental   # Las tablas grandes usan incremental

      # Subcarpeta google_sheets (fuente de presupuestos)
      google_sheets:
        +database: ALUMNO18_DEV_SILVER_DB
        +schema: SILVER
        +materialized: view          # Normalmente liviana y actualizable completa

    # ========================================================
    # CAPA GOLD (Marts)
    # ========================================================
    # Si más adelante agregas tus modelos analíticos o dimensionales,
    # puedes crearlos aquí. Ahora mismo no los usamos, pero ya queda preparado.
    marts:
      +database: ALUMNO18_DEV_GOLD_DB
      +schema: GOLD
      +materialized: table
