name: 'my_new_project'
version: '1.0.0'
config-version: 2

# Usa aquí el profile que realmente tienes en dbt Cloud.
# Por los logs parece ser "user", pero si en tu Cloud pone "default",
# cambia esto a 'default'.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:

    # ============================
    # STAGING (= SILVER LÓGICA)
    # ============================
    staging:
      # Todo lo que esté bajo models/staging/** irá a la BD SILVER
      +database: ALUMNO18_DEV_SILVER_DB
      # Esquema Silver que usas tú
      +schema: dbt_jparejanieto_SILVER

      # Por defecto, si no se indica otra cosa, serán vistas
      +materialized: view

      # Subcarpeta SQL Server (Bronze: SQL_SERVER_DBO)
      sql_server_dbo:
        +tags: ["silver", "sql_server_dbo"]

      # Subcarpeta Google Sheets (Bronze: GOOGLE_SHEETS)
      google_sheets:
        +tags: ["silver", "google_sheets"]

    # ============================
    # MARTS (= GOLD)
    # ============================
    marts:
      # Aquí construiremos la capa analítica/final
      +database: ALUMNO18_DEV_GOLD_DB
      # Puedes cambiar PUBLIC por otro esquema si te han creado uno para ti
      +schema: PUBLIC

      # Por defecto, las tablas Gold se materializan como TABLE
      +materialized: table

      # Puedes crear subcarpetas como models/marts/core, models/marts/marketing, etc.
      core:
        +tags: ["gold", "core"]
